global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Scrape LiteLLM app - using internal communication only
  - job_name: 'litellm'
    static_configs:
      # Internal communication trong Container App Environment
      - targets: ['litellm-app:4000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
